databases:
  - name: budget
    databaseName: budget_na6e
    user: budget_na6e_user

services:
  - type: web
    name: budgetappgra
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_na6e
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
